from django.db import models

# Create your models here.
class Disclosure(models.Model):
    upload_key = models.CharField(max_length=150, blank=True, null=True)
    job_start_date = models.CharField(max_length=150, blank=True, null=True)
    job_end_date = models.CharField(max_length=150, blank=True, null=True)
    api_number = models.CharField(max_length=14, blank=True, null=True)
    state_number = models.CharField(max_length=2, blank=True, null=True)
    county_number = models.CharField(max_length=3, blank=True, null=True)
    operator_name = models.CharField(max_length=55, blank=True, null=True)
    well_name = models.CharField(max_length=150, blank=True, null=True)
    latitude = models.FloatField(blank=True, null=True)
    longitude = models.FloatField(blank=True, null=True)
    projection = models.CharField(max_length=150, blank=True, null=True)
    tvd = models.FloatField(blank=True, null=True)
    total_base_water_volume = models.FloatField(blank=True, null=True)
    total_base_nonwater_volume = models.FloatField(blank=True, null=True)
    state_name = models.CharField(max_length=150, blank=True, null=True)
    county_name = models.CharField(max_length=150, blank=True, null=True)
    ff_version = models.BigIntegerField(blank=True, null=True)
    federal_well = models.BooleanField(blank=True, null=True)
    indian_well = models.BooleanField(blank=True, null=True)
    source = models.FloatField(blank=True, null=True)
    dtmod = models.FloatField(blank=True, null=True)
    purpose_key = models.CharField(max_length=150, blank=True, null=True)
    trade_name = models.CharField(max_length=150, blank=True, null=True)
    supplier = models.CharField(max_length=150, blank=True, null=True)
    purpose = models.CharField(max_length=150, blank=True, null=True)
    system_approach = models.FloatField(blank=True, null=True)
    is_water = models.FloatField(blank=True, null=True)
    purpose_percent_hf_job = models.FloatField(blank=True, null=True)
    purpose_ingredient_msds = models.FloatField(blank=True, null=True)
    ingredient_key = models.CharField(max_length=150, primary_key=True)
    ingredient_name = models.CharField(max_length=150,blank=True, null=True)
    cas_number = models.CharField(max_length=20, blank=True, null=True)
    percent_high_additive = models.FloatField(blank=True, null=True)
    percent_hf_job = models.FloatField(blank=True, null=True)
    ingredient_comment = models.CharField(max_length=150, blank=True, null=True)
    ingredient_msds = models.BooleanField(blank=True, null=True)
    mass_ingredient = models.FloatField(blank=True, null=True)
    claimant_company = models.CharField(max_length=150, blank=True, null=True)
    disclosure_key = models.CharField(max_length=150)
    basin = models.CharField(max_length=150, blank=True, null=True)
    chloride_mean = models.FloatField(blank=True, null=True)
    chloride_std = models.FloatField(blank=True, null=True)
    pH_mean = models.FloatField(blank=True, null=True)
    pH_std = models.FloatField(blank=True, null=True)
    bromide_mean = models.FloatField(blank=True, null=True)
    bromide_std = models.FloatField(blank=True, null=True)
    iodide_mean = models.FloatField(blank=True, null=True)
    iodide_std = models.FloatField(blank=True, null=True)
    temperature_mean = models.FloatField(blank=True, null=True)
    temperature_std = models.FloatField(blank=True, null=True)
    cas_number_corrected = models.CharField(max_length=150, blank=True, null=True)
    cas_chem_match = models.BooleanField(blank=True, null=True)
    chem_cas_corrected = models.BooleanField(blank=True, null=True)
    well_depth = models.FloatField(blank=True, null=True)


    def __str__(self):
        return self.cas_number_corrected + 'at ({}, {})'.format(self.latitude, self.longitude)



