# Generated by Django 3.0.7 on 2020-08-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlowbackMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=150)),
                ('api_number', models.CharField(max_length=14)),
                ('state_number', models.CharField(max_length=2)),
                ('county_number', models.CharField(max_length=3)),
                ('well_name', models.CharField(max_length=150)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('compound_name', models.CharField(max_length=150)),
                ('cas_number', models.CharField(max_length=20)),
                ('method', models.CharField(max_length=150)),
                ('concentration', models.FloatField()),
                ('standard_deviation', models.FloatField()),
                ('reference', models.CharField(max_length=150)),
            ],
        ),
    ]
