# Generated by Django 3.0.7 on 2020-08-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disclosure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_key', models.CharField(max_length=150)),
                ('job_start_date', models.DateTimeField()),
                ('job_end_date', models.DateTimeField()),
                ('api_number', models.CharField(max_length=14)),
                ('state_number', models.CharField(max_length=2)),
                ('county_number', models.CharField(max_length=3)),
                ('operator_name', models.CharField(max_length=55)),
                ('well_name', models.CharField(max_length=150)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('projection', models.CharField(max_length=150)),
                ('tvd', models.FloatField()),
                ('total_base_water_volume', models.FloatField()),
                ('total_base_nonwater_volume', models.FloatField()),
                ('state_name', models.CharField(max_length=150)),
                ('county_name', models.CharField(max_length=150)),
                ('ff_version', models.BigIntegerField()),
                ('federal_well', models.BooleanField()),
                ('indian_well', models.BooleanField()),
                ('source', models.FloatField()),
                ('dtmod', models.FloatField()),
                ('purpose_key', models.CharField(max_length=150)),
                ('trade_name', models.CharField(max_length=150)),
                ('supplier', models.CharField(max_length=150)),
                ('purpose', models.CharField(max_length=150)),
                ('system_approach', models.FloatField()),
                ('is_water', models.FloatField()),
                ('purpose_percent_hf_job', models.FloatField()),
                ('purpose_ingredient_msds', models.FloatField()),
                ('ingredient_key', models.CharField(max_length=150)),
                ('ingredient_name', models.CharField(max_length=150)),
                ('cas_number', models.CharField(max_length=20)),
                ('percent_high_additive', models.FloatField()),
                ('percent_hf_job', models.FloatField()),
                ('ingredient_comment', models.CharField(max_length=150)),
                ('ingredient_msds', models.BooleanField()),
                ('mass_ingredient', models.FloatField()),
                ('claimant_company', models.CharField(max_length=150)),
                ('disclosure_key', models.CharField(max_length=150)),
                ('basin', models.CharField(max_length=150)),
                ('chloride_mean', models.FloatField()),
                ('chloride_std', models.FloatField()),
                ('pH_mean', models.FloatField()),
                ('pH_std', models.FloatField()),
                ('bromide_mean', models.FloatField()),
                ('bromide_std', models.FloatField()),
                ('iodide_mean', models.FloatField()),
                ('iodide_std', models.FloatField()),
                ('temperature_mean', models.FloatField()),
                ('temperature_std', models.FloatField()),
                ('cas_number_corrected', models.CharField(max_length=150)),
                ('cas_chem_match', models.BooleanField()),
                ('chem_cas_corrected', models.BooleanField()),
                ('well_depth', models.FloatField()),
            ],
        ),
    ]
